package Controller;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import Model.SumaModelo;
import javafx.event.ActionEvent;

public class Controller {
	@FXML
	private Button txtsumar;
	@FXML
	private TextField txtOpen1;
	@FXML
	private TextField txtOpen2;
	@FXML
	private TextField txtResultado;

	// Event Listener on Button[#txtsumar].onAction
	@FXML
	public void suma(ActionEvent event) {
		// TODO Autogenerated
		
		try {
			int op1 = Integer.parseInt(this.txtOpen1.getText());
			int op2 = Integer.parseInt(this.txtOpen2.getText());
			
			SumaModelo su = new SumaModelo(op1, op2);
			
			int resultado = su.sumarN();
			
			this.txtResultado.setText(resultado+"");
			
			
		} catch (NumberFormatException e) {
			
			Alert alert = new Alert(Alert.AlertType.ERROR);
			alert.setHeaderText(null);
			alert.setTitle("Error");
			alert.setContentText("Formato incorrento");
			alert.showAndWait();
		}
		
		
	}
}
